#!/usr/bin/perl -w

# TODO: Convert to a python script.
# TODO: Pass in args for nsrc, output dir prefix, topology, bandwidth, etc etc

use strict;

use Cwd;

my $dir = getcwd;

my $whiskerdir = $dir . q{/../../../tcp/remy/rats/new/};

if (-d "results/Dumbbell") {
     print "Will not run, results/Dumbbell already exists. Either delete it or specify another directory.\n";
     exit 1;
}

if (-d "results/Dumbbell-rational-delta0.1") {
     print "Will not run, results/Dumbbell-rational-delta0.1 already exists. Either delete it or specify another directory.\n";
     exit 1;
}

if (-d "results/Dumbbell-rational-delta1") {
     print "Will not run, results/Dumbbell-rational-delta1 already exists. Either delete it or specify another directory.\n";
     exit 1;
}

if (-d "results/Dumbbell-rational-delta10") {
     print "Will not run, results/Dumbbell-rational-delta10 already exists. Either delete it or specify another directory.\n";
     exit 1;
}

for my $nsrc ( 8 ) { # maximum degree of multiplexing
    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/Newreno -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/Linux/cubic -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/Linux/compound -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/Vegas -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/Reno/XCP -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p Cubic/sfqCoDel -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/MaxThroughput -n $nsrc &";

    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb -p TCP/MinDelay -n $nsrc &";

#    system qq{python runremy.py -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -d results/Dumbbell  -p TCP/NaiveQ -n $nsrc &};

    $ENV{ WHISKERS } = $whiskerdir . q{delta0.1.dna};
    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb-rational-delta0.1  -p TCP/Rational -n $nsrc &";

    $ENV{'WHISKERS'} = $whiskerdir . q{delta1.dna};
    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb-rational-delta1  -p TCP/Rational -n $nsrc &";

    $ENV{'WHISKERS'} = $whiskerdir . q{delta10.dna};
    system "python runremy.py".
        " -c remyconf/dumbbell-buf1000-rtt150-bneck15.tcl -b 5Mb".
        " -d experiments/bneck-5Mb/Dumbbell5Mb-rational-delta10  -p TCP/Rational -n $nsrc &";
}
